name: CI

on:
  pull_request: null

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        php-versions: ['7.3', '7.4', '8.0', '8.1']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: xmlreader, xmlwriter, gmp, mbstring
        tools: composer

    - name: Install Dependencies
      run: composer install --prefer-dist

    - name: Run PHPUnit
      run: ./vendor/bin/phpunit
