name: CI

on:
  push:
    branches: [main]
  pull_request: null
  workflow_dispatch: null

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        php-versions: ['7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: xmlreader, xmlwriter, gmp, mbstring
        tools: composer

    - name: Install Dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Validate Composer Metadata
      run: composer validate --strict --no-check-publish

    - name: Run PHPUnit
      run: composer test
